import { Course } from "@/lib/types";

export const courses: Course[] = [
  {
    id: 1,
    name: "פיתוח אפליקציות מובייל",
    nameChangeRequired: false,
    type: "certificate",
    aboutFile: "about-course-1.pdf",
    syllabusRequired: true,
    learningHours: "40 שעות, 8 פרקים",
    surveysAdded: true,
    gradingPercentages: "70% מבחן, 30% מטלות",
    marketingImagesAvailable: true,
    marketingImagesLink: "https://example.com/images",
    clientLogo: "logo-1.png",
    certificateSignature: "signature-1.png",
    supportContact: "support@example.com",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: 2,
    name: "מבוא למדעי המחשב",
    nameChangeRequired: true,
    newName: "מבוא למדעי המחשב - עדכון",
    type: "no_certificate",
    syllabusRequired: false,
    surveysAdded: false,
    marketingImagesAvailable: false,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: 3,
    name: "אבטחת מידע ברשת",
    nameChangeRequired: false,
    type: "certificate",
    syllabusRequired: true,
    syllabusFile: "syllabus-3.pdf",
    surveysAdded: true,
    gradingFile: "grading-model-3.pdf",
    marketingImagesAvailable: true,
    clientLogo: "logo-3.png",
    createdAt: new Date("2024-02-10"),
  },
];
